name: Lint source code

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  UV_SYSTEM_PYTHON: "1"  # make uv do global installs

jobs:
  # If you update any of these commands, don't forget to update the equivalent
  # tox environment
  uv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv pip install ".[lint,test]"

  ruff:
    needs: uv
    runs-on: ubuntu-latest

    steps:
    - name: Lint with Ruff
      run: ruff check --output-format=github

    - name: Format with Ruff
      run: ruff format --diff

  flake8:
    needs: uv
    runs-on: ubuntu-latest

    steps:
    - name: Lint with flake8
      run: uvx --from 'flake8>=6.0' flake8 .

  mypy:
    needs: uv
    runs-on: ubuntu-latest

    steps:
    - name: Type check with mypy
      run: mypy

  pyright:
    needs: uv
    runs-on: ubuntu-latest

    steps:
    - name: Type check with pyright
      run: pyright

  docs-lint:
    needs: uv
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: uv tool install sphinx-lint
    - name: Lint documentation with sphinx-lint
      run: make doclinter

  twine:
    needs: uv
    runs-on: ubuntu-latest

    steps:
    - name: Lint with twine
      run: |
        uvx build .
        uvx twine check dist/*
